// WSET Level 3 Theory question bank.
// Each: { q, options[4], answer, category, why }
// Categories: viticulture, vinification, france, italy, iberia, germanic,
//             newworld, sparkling, fortified, consumer

const THEORY_QUESTIONS = [
  // ---------- VITICULTURE ----------
  { q: "Why does a vineyard on a slope generally ripen grapes more reliably than one on a flat valley floor in a cool climate?", options: ["Slopes have richer, more fertile soil", "Slopes get better sun exposure and drain cold air downhill", "Flat land holds more water for the vine", "Slopes are always closer to moderating water"], answer: "Slopes get better sun exposure and drain cold air downhill", category: "viticulture", why: "Aspect (angle to the sun) boosts ripening, and cold air drains away downslope rather than pooling around the vines — reducing frost risk. Valley floors are classic frost pockets." },
  { q: "What is the primary purpose of canopy management techniques like leaf removal?", options: ["To increase total yield", "To control sunlight and airflow around the grapes", "To raise the vine's water uptake", "To delay budburst"], answer: "To control sunlight and airflow around the grapes", category: "viticulture", why: "Managing the canopy controls light exposure (ripening, flavour development) and airflow (reducing fungal disease) around the fruit zone — central to quality." },
  { q: "A 'continental' climate is characterised by:", options: ["Low difference between summer and winter temperatures", "A large difference between summer and winter temperatures", "Constant rainfall year-round", "Strong maritime moderation"], answer: "A large difference between summer and winter temperatures", category: "viticulture", why: "Continental climates (e.g. Burgundy, much of Germany) have hot summers and cold winters — a wide annual range, with the risk of spring frost and a short growing season." },
  { q: "Which of these is a method of frost protection in the vineyard?", options: ["Green harvesting", "Wind machines that mix warmer air down to the vines", "Malolactic conversion", "Extended maceration"], answer: "Wind machines that mix warmer air down to the vines", category: "viticulture", why: "Frost protection methods include wind machines, sprinklers (latent heat of freezing), and heaters/bougies. Green harvest and the others relate to yield or winemaking, not frost." },
  { q: "What does 'noble rot' (Botrytis cinerea) do to grapes under the right conditions?", options: ["Increases yield dramatically", "Concentrates sugars and adds complexity for sweet wines", "Removes all acidity", "Prevents any fungal disease"], answer: "Concentrates sugars and adds complexity for sweet wines", category: "viticulture", why: "In dry-then-humid conditions botrytis dehydrates grapes, concentrating sugar/acid and adding honeyed, dried-fruit complexity — essential for Sauternes, Tokaji, and German/Austrian sweet wines." },
  { q: "Why might a grower deliberately reduce yields through green harvesting?", options: ["To increase concentration in the remaining grapes", "To speed up budburst", "To raise acidity directly", "To prevent malolactic conversion"], answer: "To increase concentration in the remaining grapes", category: "viticulture", why: "Removing some bunches (green harvest) channels the vine's resources into fewer grapes, generally improving concentration and ripeness — a quality-over-quantity choice." },
  { q: "A maritime climate differs from a Mediterranean climate primarily in that maritime climates have:", options: ["Hotter summers", "Rainfall spread throughout the year", "No moderating water influence", "Dry, warm summers"], answer: "Rainfall spread throughout the year", category: "viticulture", why: "Both are moderate, but maritime climates (e.g. Bordeaux) have year-round rainfall, while Mediterranean climates (e.g. coastal Spain, parts of California) have notably dry, warm summers." },
  { q: "Which soil characteristic is generally most valued for wine quality, rather than soil fertility?", options: ["High organic richness", "Good drainage", "Maximum water retention", "Dark colour for warmth only"], answer: "Good drainage", category: "viticulture", why: "Free-draining soils stress the vine slightly and prevent waterlogging, favouring quality over vigour. High fertility tends to push leafy growth and dilute fruit." },

  // ---------- VINIFICATION ----------
  { q: "What is malolactic conversion (MLF)?", options: ["Conversion of sugar to alcohol", "Conversion of sharp malic acid to softer lactic acid", "Removal of tannins", "Addition of sweetness"], answer: "Conversion of sharp malic acid to softer lactic acid", category: "vinification", why: "MLF is carried out by bacteria, softening acidity (malic to lactic) and adding buttery notes. Used on nearly all reds and many fuller whites like oaked Chardonnay; often avoided for crisp aromatic whites." },
  { q: "Why is fermentation temperature kept cooler for many aromatic white wines?", options: ["To extract more tannin", "To preserve delicate fruit and floral aromas", "To speed up fermentation", "To encourage oxidation"], answer: "To preserve delicate fruit and floral aromas", category: "vinification", why: "Cool fermentation (around 12-16°C) retains volatile aromatic compounds in whites. Reds ferment warmer to extract colour and tannin from the skins." },
  { q: "What does extended maceration (keeping juice on skins after fermentation) primarily affect in red wine?", options: ["Sweetness", "Colour, tannin and flavour extraction", "Alcohol level", "Acidity only"], answer: "Colour, tannin and flavour extraction", category: "vinification", why: "Time on skins governs how much colour, tannin, and flavour is extracted. More extraction builds structure and ageability; gentler handling keeps wines softer and fruitier." },
  { q: "What flavour does new oak most commonly contribute to wine?", options: ["Green pepper", "Vanilla, toast and spice", "Gooseberry", "Petrol"], answer: "Vanilla, toast and spice", category: "vinification", why: "New oak imparts vanilla, toast, smoke, clove, and (American oak) coconut/dill. Older/neutral oak contributes little flavour but still allows slow oxygenation and texture." },
  { q: "What is the purpose of lees stirring (bâtonnage)?", options: ["To remove all yeast", "To add creamy texture and body", "To increase acidity", "To strip colour"], answer: "To add creamy texture and body", category: "vinification", why: "Stirring dead yeast cells (lees) back into the wine adds a creamy, savoury texture and body — common in oaked Chardonnay and some other premium whites." },
  { q: "Fining and filtration are both used to:", options: ["Increase tannin", "Clarify and stabilise the wine before bottling", "Add flavour", "Raise alcohol"], answer: "Clarify and stabilise the wine before bottling", category: "vinification", why: "Both clarify the wine: fining binds and removes haze-causing particles (egg white, bentonite), filtration physically strains the wine. Both improve clarity and stability." },
  { q: "Carbonic maceration, used notably in Beaujolais, produces wines that are:", options: ["High in tannin and age-worthy", "Fruity, light, with low tannin", "Deeply oxidative", "Always sweet"], answer: "Fruity, light, with low tannin", category: "vinification", why: "Whole-bunch fermentation in a CO2-rich environment yields bright, fruity, low-tannin reds with signature banana/pear-drop/bubblegum notes — the Beaujolais Nouveau style." },
  { q: "Which winemaking choice would most increase a red wine's capacity to age?", options: ["Cool fermentation and early bottling", "Significant tannin extraction and new oak maturation", "Avoiding malolactic conversion", "Carbonic maceration"], answer: "Significant tannin extraction and new oak maturation", category: "vinification", why: "Tannin and oak-derived compounds act as structural and antioxidant scaffolding, letting a wine evolve slowly over years. Light, fruity styles are made for early drinking." },
  { q: "Chaptalisation refers to:", options: ["Adding acid to must", "Adding sugar to the must to raise final alcohol", "Removing water", "Adding tannin"], answer: "Adding sugar to the must to raise final alcohol", category: "vinification", why: "Permitted in cooler regions where grapes may not reach full ripeness, chaptalisation adds sugar before/during fermentation to boost alcohol — it does not sweeten the finished wine." },

  // ---------- FRANCE ----------
  { q: "In Burgundy, the top tier of the vineyard classification hierarchy is:", options: ["Village", "Premier Cru", "Grand Cru", "Régionale"], answer: "Grand Cru", category: "france", why: "Burgundy's pyramid runs Régionale → Village → Premier Cru → Grand Cru at the top. Grand Cru vineyards are individually named and represent the most prized sites." },
  { q: "The principal red grape of the Côte d'Or in Burgundy is:", options: ["Gamay", "Pinot Noir", "Syrah", "Merlot"], answer: "Pinot Noir", category: "france", why: "Burgundy's Côte d'Or reds are Pinot Noir; its whites are Chardonnay. Gamay is the grape of Beaujolais to the south." },
  { q: "A red Bordeaux from the Left Bank (e.g. Pauillac) is typically dominated by:", options: ["Merlot", "Cabernet Sauvignon", "Cabernet Franc", "Malbec"], answer: "Cabernet Sauvignon", category: "france", why: "Left Bank (Médoc, Graves) blends are Cabernet Sauvignon-dominant on gravel soils; Right Bank (Saint-Émilion, Pomerol) leans Merlot. Knowing the bank tells you the blend." },
  { q: "Which Rhône appellation is famous for a red blend permitting up to 13 grape varieties, led by Grenache?", options: ["Hermitage", "Côte-Rôtie", "Châteauneuf-du-Pape", "Condrieu"], answer: "Châteauneuf-du-Pape", category: "france", why: "Southern Rhône's Châteauneuf-du-Pape is Grenache-led (with Syrah, Mourvèdre etc.). Northern Rhône reds (Hermitage, Côte-Rôtie) are Syrah; Condrieu is white Viognier." },
  { q: "Sancerre and Pouilly-Fumé, in the Loire, are made from which grape?", options: ["Chenin Blanc", "Sauvignon Blanc", "Melon de Bourgogne", "Chardonnay"], answer: "Sauvignon Blanc", category: "france", why: "These eastern Loire appellations are benchmark Sauvignon Blanc — flinty, high-acid. Chenin Blanc dominates the middle Loire (Vouvray), Melon de Bourgogne the Muscadet region." },
  { q: "Alsace is unusual in France for labelling its wines primarily by:", options: ["Region only", "Grape variety", "Vineyard only", "Producer only"], answer: "Grape variety", category: "france", why: "Alsace is one of the few French regions to label by varietal (Riesling, Gewürztraminer, Pinot Gris, Muscat) — a legacy of its Germanic history." },
  { q: "Which grape is the sole permitted red variety in red Beaujolais?", options: ["Pinot Noir", "Gamay", "Grenache", "Cinsault"], answer: "Gamay", category: "france", why: "Beaujolais reds are 100% Gamay, often made via carbonic maceration. The ten Beaujolais Crus (Morgon, Fleurie etc.) make the most serious, age-worthy examples." },
  { q: "The sweet wines of Sauternes owe their character primarily to:", options: ["Late frost", "Noble rot (Botrytis cinerea)", "Fortification", "Drying grapes on mats"], answer: "Noble rot (Botrytis cinerea)", category: "france", why: "Sauternes (Sémillon-led) relies on morning mists off the Ciron river inducing botrytis, which concentrates sugars for its honeyed sweet style." },
  { q: "Which classification term on a French label indicates the highest general EU quality category?", options: ["Vin de France", "IGP", "AOC/AOP", "Vin de Table"], answer: "AOC/AOP", category: "france", why: "AOC/AOP (Appellation d'Origine Contrôlée/Protégée) is the top tier with the strictest rules on origin, grapes, and methods. IGP is the broader regional tier below it." },

  // ---------- ITALY ----------
  { q: "Chianti and Brunello di Montalcino are both based on which grape?", options: ["Nebbiolo", "Sangiovese", "Barbera", "Montepulciano"], answer: "Sangiovese", category: "italy", why: "Tuscany's flagship reds — Chianti, Brunello, Vino Nobile — are all Sangiovese-based. High acidity and savoury sour-cherry/tomato-leaf notes are its signature." },
  { q: "Barolo and Barbaresco, in Piedmont, are made from:", options: ["Sangiovese", "Nebbiolo", "Corvina", "Primitivo"], answer: "Nebbiolo", category: "italy", why: "Piedmont's two most prestigious reds are Nebbiolo — pale, intensely tannic and high-acid, with tar and dried rose aromas. Not to be confused with Tuscan Sangiovese." },
  { q: "What does the Italian quality designation 'DOCG' stand at, relative to 'DOC'?", options: ["Below DOC", "The same as DOC", "Above DOC, with stricter rules", "Outside the quality system"], answer: "Above DOC, with stricter rules", category: "italy", why: "DOCG (Denominazione di Origine Controllata e Garantita) sits above DOC, with tighter regulations and a guarantee of origin/quality. Both are above IGT and generic wine." },
  { q: "Soave, a white wine from Veneto, is made principally from:", options: ["Pinot Grigio", "Garganega", "Trebbiano only", "Cortese"], answer: "Garganega", category: "italy", why: "Soave is Garganega-based. Knowing the lead grape behind regional names (Soave→Garganega, Gavi→Cortese) is exactly the kind of detail the exam tests." },
  { q: "Amarone della Valpolicella achieves its full, high-alcohol style through:", options: ["Fortification", "Drying grapes before fermentation (appassimento)", "Botrytis", "Carbonic maceration"], answer: "Drying grapes before fermentation (appassimento)", category: "italy", why: "Amarone uses appassimento — drying Corvina-based grapes on racks for months to concentrate sugar — producing a rich, high-alcohol, often raisined dry red." },

  // ---------- IBERIA (Spain & Portugal still) ----------
  { q: "Spanish Rioja is based principally on which red grape?", options: ["Garnacha", "Tempranillo", "Monastrell", "Mencía"], answer: "Tempranillo", category: "iberia", why: "Rioja is Tempranillo-led (often with some Garnacha). Its traditional style shows American-oak vanilla, dill, and coconut, with leather and tobacco as it ages." },
  { q: "On a Rioja label, 'Gran Reserva' indicates:", options: ["No oak ageing", "The longest minimum ageing requirement", "A sweet wine", "A sparkling wine"], answer: "The longest minimum ageing requirement", category: "iberia", why: "Spain's ageing ladder runs Joven → Crianza → Reserva → Gran Reserva, the last requiring the most extended oak and bottle ageing before release." },
  { q: "The Spanish white grape Albariño, making crisp, saline wines, is most associated with:", options: ["Rías Baixas", "Jerez", "Priorat", "La Mancha"], answer: "Rías Baixas", category: "iberia", why: "Albariño thrives in cool, coastal Rías Baixas (Galicia), giving high-acid, citrus and saline whites — a contrast to Spain's warmer inland reds." },
  { q: "Portugal's Vinho Verde is best known for being:", options: ["A rich, oaked red", "A light, fresh, often slightly spritzy white", "A fortified dessert wine", "A sweet botrytised wine"], answer: "A light, fresh, often slightly spritzy white", category: "iberia", why: "Vinho Verde ('green wine') from northern Portugal is light, low-alcohol, high-acid and sometimes faintly fizzy — made for early drinking." },
  { q: "The Douro Valley in Portugal is the home of which famous wine (in its fortified form)?", options: ["Sherry", "Port", "Madeira", "Marsala"], answer: "Port", category: "iberia", why: "Port is produced in the Douro from grapes like Touriga Nacional. (Sherry is from Jerez in Spain; Madeira from the Portuguese island of the same name.)" },

  // ---------- GERMANIC + TOKAJ ----------
  { q: "On a German label, what does 'Trocken' mean?", options: ["Sweet", "Dry", "Sparkling", "Fortified"], answer: "Dry", category: "germanic", why: "'Trocken' means dry. German sweetness terms are essential: Trocken (dry), Halbtrocken (off-dry), and the Prädikat ripeness ladder signalling potential sweetness." },
  { q: "The German Prädikat levels (Kabinett, Spätlese, Auslese...) are based on:", options: ["Vineyard size", "Grape ripeness/sugar at harvest", "Oak ageing", "Bottle ageing"], answer: "Grape ripeness/sugar at harvest", category: "germanic", why: "Prädikat tiers reflect must weight (ripeness) at harvest, ascending Kabinett → Spätlese → Auslese → Beerenauslese → Trockenbeerenauslese → (Eiswein). Higher ripeness, not necessarily sweetness." },
  { q: "Which grape dominates Germany's finest wines, capable of bone-dry to lusciously sweet styles?", options: ["Müller-Thurgau", "Riesling", "Silvaner", "Grüner Veltliner"], answer: "Riesling", category: "germanic", why: "Riesling is Germany's noble grape — high-acid, transparent to site, age-worthy, and developing petrol notes with age. The Mosel and Rheingau are benchmark regions." },
  { q: "Grüner Veltliner is the signature white grape of which country?", options: ["Germany", "Austria", "Hungary", "Switzerland"], answer: "Austria", category: "germanic", why: "Grüner Veltliner is Austria's flagship — dry, high-acid, peppery whites, especially from the Wachau, Kamptal, and Kremstal." },
  { q: "Tokaji Aszú, Hungary's famous sweet wine, gets its sweetness from:", options: ["Fortification", "Botrytis-affected (aszú) berries", "Ice harvest", "Added grape spirit"], answer: "Botrytis-affected (aszú) berries", category: "germanic", why: "Tokaji Aszú is made by adding botrytised aszú berries (mainly Furmint) to base wine, measured historically in 'puttonyos' — concentrated, honeyed, and high-acid." },

  // ---------- NEW WORLD ----------
  { q: "Marlborough, New Zealand built its global reputation on which grape?", options: ["Pinot Noir", "Sauvignon Blanc", "Chardonnay", "Riesling"], answer: "Sauvignon Blanc", category: "newworld", why: "Marlborough Sauvignon Blanc — pungent, with gooseberry, passionfruit, and grassy/herbaceous intensity — became a global benchmark style from the 1980s onward." },
  { q: "Argentina's signature red grape, thriving at high altitude in Mendoza, is:", options: ["Carmenère", "Malbec", "Tannat", "Bonarda"], answer: "Malbec", category: "newworld", why: "Malbec found its global home in Mendoza, where high-altitude sites give deeply coloured, plush reds with plum, blackberry, and violet — softer than its French origins in Cahors." },
  { q: "Chile's distinctive red grape, once confused with Merlot, is:", options: ["Malbec", "Carmenère", "Pinotage", "Zinfandel"], answer: "Carmenère", category: "newworld", why: "Carmenère is Chile's signature, long mistaken for Merlot in its vineyards. It gives ripe red/black fruit with a characteristic green, herbaceous edge if underripe." },
  { q: "Pinotage, a grape largely unique to South Africa, is a crossing of:", options: ["Pinot Noir and Cinsault", "Syrah and Grenache", "Cabernet and Merlot", "Pinot Noir and Syrah"], answer: "Pinot Noir and Cinsault", category: "newworld", why: "Pinotage was bred in South Africa from Pinot Noir × Cinsault (locally 'Hermitage'). It yields bold reds, sometimes with smoky or banana notes depending on winemaking." },
  { q: "The Barossa Valley in Australia is especially renowned for which full-bodied red?", options: ["Pinot Noir", "Shiraz", "Grenache", "Cabernet Franc"], answer: "Shiraz", category: "newworld", why: "Warm Barossa Shiraz is a flagship Australian style — rich, high-alcohol, with dark fruit, chocolate, spice, and often black olive/savoury notes." },
  { q: "California's Napa Valley is most prestigious for which grape?", options: ["Zinfandel", "Cabernet Sauvignon", "Pinot Noir", "Chardonnay"], answer: "Cabernet Sauvignon", category: "newworld", why: "Napa's reputation (and pricing) rests on Cabernet Sauvignon — ripe, full-bodied, oak-influenced. Cooler areas like Carneros and Sonoma Coast favour Pinot Noir and Chardonnay." },
  { q: "Which region is correctly paired with a cool-climate style suited to Pinot Noir?", options: ["Barossa Valley, Australia", "Central Otago, New Zealand", "La Mancha, Spain", "Mendoza floor, Argentina"], answer: "Central Otago, New Zealand", category: "newworld", why: "Central Otago is one of the world's southernmost, coolest wine regions — ideal for high-acid, perfumed Pinot Noir. The others are warm-climate regions." },
  { q: "Stellenbosch and the broader Western Cape, with their cooling ocean influence, belong to which country?", options: ["Australia", "Chile", "South Africa", "USA"], answer: "South Africa", category: "newworld", why: "Stellenbosch is South Africa's most famous quality region, where the Atlantic's Benguela current and the 'Cape Doctor' wind moderate the warm climate." },

  // ---------- SPARKLING ----------
  { q: "What defines the 'traditional method' of sparkling wine production?", options: ["Bubbles injected into the tank", "Second fermentation in the bottle", "Fermentation stopped early", "Adding CO2 at bottling"], answer: "Second fermentation in the bottle", category: "sparkling", why: "The traditional method (Champagne, Cava, quality English sparkling) creates bubbles via a second fermentation inside the bottle, with lees ageing adding biscuity, brioche complexity." },
  { q: "Which grapes are the three principal varieties of Champagne?", options: ["Chardonnay, Riesling, Pinot Noir", "Chardonnay, Pinot Noir, Pinot Meunier", "Chenin, Chardonnay, Pinot Noir", "Pinot Noir, Gamay, Chardonnay"], answer: "Chardonnay, Pinot Noir, Pinot Meunier", category: "sparkling", why: "Champagne is built on Chardonnay (finesse), Pinot Noir (structure/body), and Pinot Meunier (fruit/approachability). 'Blanc de Blancs' = Chardonnay only; 'Blanc de Noirs' = black grapes only." },
  { q: "Prosecco is made primarily using which production method?", options: ["Traditional method", "Tank (Charmat) method", "Carbonation", "Transfer method"], answer: "Tank (Charmat) method", category: "sparkling", why: "Prosecco's second fermentation happens in a pressurised tank, not the bottle — preserving fresh, fruity, floral Glera character rather than developing autolytic biscuit notes." },
  { q: "On a Champagne label, 'Brut' indicates the wine is:", options: ["Sweet", "Dry", "Medium-sweet", "Still"], answer: "Dry", category: "sparkling", why: "Sweetness rises: Brut Nature/Extra Brut (driest) → Brut → Extra Dry → Sec → Demi-Sec → Doux. Brut is dry and by far the most common style." },
  { q: "What does the dosage do in traditional method sparkling wine?", options: ["Triggers the first fermentation", "Adjusts the final sweetness after disgorgement", "Removes the lees", "Adds the bubbles"], answer: "Adjusts the final sweetness after disgorgement", category: "sparkling", why: "After disgorgement removes the lees sediment, a 'liqueur d'expédition' (dosage) tops up the bottle and sets the final sweetness level — from zero (Brut Nature) upward." },
  { q: "Cava, Spain's traditional-method sparkling wine, is produced mainly in:", options: ["Rioja", "Catalonia (Penedès)", "Jerez", "Galicia"], answer: "Catalonia (Penedès)", category: "sparkling", why: "Most Cava comes from Catalonia, using traditional-method production with local grapes (Macabeo, Xarel-lo, Parellada) — offering traditional-method complexity at accessible prices." },
  { q: "The biscuit/brioche/toast aromas in vintage Champagne come primarily from:", options: ["New oak", "Extended ageing on the lees (autolysis)", "Botrytis", "Added flavouring"], answer: "Extended ageing on the lees (autolysis)", category: "sparkling", why: "Autolysis — the breakdown of dead yeast cells during long lees contact — generates the signature bready, biscuity complexity of fine traditional-method sparkling wine." },

  // ---------- FORTIFIED ----------
  { q: "Fino and Manzanilla Sherry develop their distinctive tangy, savoury character through:", options: ["Long oak ageing only", "Ageing under a layer of yeast called flor", "Botrytis", "Drying grapes"], answer: "Ageing under a layer of yeast called flor", category: "fortified", why: "Flor is a film of yeast that grows on the wine's surface, protecting it from oxygen and imparting Fino/Manzanilla's pungent, saline, bone-dry style ('biological ageing')." },
  { q: "Oloroso Sherry differs from Fino because it is aged:", options: ["Under flor", "Oxidatively, without flor", "In bottle only", "With added sweetness always"], answer: "Oxidatively, without flor", category: "fortified", why: "Oloroso is fortified higher (over ~17%), preventing flor, so it ages in contact with oxygen — giving rich, nutty, dried-fruit character. Naturally dry unless sweetened." },
  { q: "What is the key difference between Ruby and Tawny Port styles?", options: ["Ruby is white; Tawny is red", "Ruby retains fresh fruit; Tawny is barrel-aged and nutty/oxidative", "Ruby is dry; Tawny is sparkling", "There is no difference"], answer: "Ruby retains fresh fruit; Tawny is barrel-aged and nutty/oxidative", category: "fortified", why: "Ruby styles (incl. Vintage) keep youthful, fresh dark-fruit character; Tawnies age in cask, oxidising to nutty, caramel, dried-fig flavours with a paler colour." },
  { q: "Port is fortified at which point, giving it natural sweetness?", options: ["After fermentation finishes", "During fermentation, stopping it early and leaving residual sugar", "Before fermentation", "Only at bottling"], answer: "During fermentation, stopping it early and leaving residual sugar", category: "fortified", why: "Adding grape spirit mid-fermentation kills the yeast while sugar remains, yielding Port's characteristic sweetness and ~19-22% alcohol. Sherry, by contrast, is fortified after a dry ferment." },
  { q: "Madeira's uniquely resilient, baked style results from:", options: ["Flor ageing", "Deliberate heating of the wine (estufagem/canteiro)", "Botrytis", "Carbonic maceration"], answer: "Deliberate heating of the wine (estufagem/canteiro)", category: "fortified", why: "Madeira is intentionally heated and oxidised — historically by long sea voyages, now via estufagem or warm canteiro lofts — giving cooked, tangy, near-indestructible wines." },
  { q: "Pedro Ximénez (PX) Sherry is characterised by being:", options: ["Bone dry and tangy", "Intensely sweet, dark, with raisin and fig notes", "Light and sparkling", "Pale and delicate"], answer: "Intensely sweet, dark, with raisin and fig notes", category: "fortified", why: "PX is made from sun-dried grapes, producing an extremely sweet, viscous, dark wine with raisin, fig, molasses, and coffee notes — often used to sweeten other Sherries too." },
  { q: "A 'Vintage' Port must be:", options: ["Aged in cask for decades before release", "From a single declared year, bottled young, aged in bottle", "A blend of many years", "Always tawny in colour"], answer: "From a single declared year, bottled young, aged in bottle", category: "fortified", why: "Vintage Port comes from one exceptional declared year, spends only ~2 years in cask, then ages for decades in bottle, throwing a sediment — the pinnacle of the Ruby family." },

  // ---------- WINE & THE CONSUMER ----------
  { q: "A classic principle of food and wine pairing is that high-acid wines:", options: ["Clash with all foods", "Pair well with fatty or rich dishes", "Only suit desserts", "Should never accompany food"], answer: "Pair well with fatty or rich dishes", category: "consumer", why: "Acidity cuts through fat and richness (think crisp white with fried food), refreshing the palate — one of the most reliable pairing levers alongside matching weight and sweetness." },
  { q: "When pairing with a sweet dessert, the wine should generally be:", options: ["Drier than the dish", "At least as sweet as the dish", "Very tannic", "Bone dry"], answer: "At least as sweet as the dish", category: "consumer", why: "A wine less sweet than the dessert tastes thin and sour by comparison. The wine should match or exceed the food's sweetness — hence dessert wines with puddings." },
  { q: "Which storage condition is best for ageing wine long-term?", options: ["Warm, bright, and upright", "Cool, dark, with stable temperature, bottles on their side", "Next to a heat source", "In frequent temperature swings"], answer: "Cool, dark, with stable temperature, bottles on their side", category: "consumer", why: "Ideal cellaring is cool (~12°C), dark, humid, vibration-free, and stable. Bottles lie down to keep corks moist. Heat and temperature swings age wine prematurely." },
  { q: "Why is a wine decanted?", options: ["Only ever to add oxygen", "To separate wine from sediment and/or aerate it", "To chill it faster", "To remove alcohol"], answer: "To separate wine from sediment and/or aerate it", category: "consumer", why: "Decanting serves two purposes: separating older wines off their sediment, and aerating young, tannic wines to soften and open them up. The reason differs by wine." },
  { q: "Very tannic red wines tend to clash with which food?", options: ["Rare red meat", "Hard cheese", "Oily fish", "Grilled steak"], answer: "Oily fish", category: "consumer", why: "Tannin reacts with oily fish to produce a metallic taste. Tannin is instead softened by protein and fat (red meat), which is why bold reds suit steak." },
  { q: "Serving temperature guidance generally suggests that full-bodied reds are best served:", options: ["Ice cold", "Lightly chilled below cellar temperature", "At around 15-18°C (slightly below room temperature)", "Warmed above room temperature"], answer: "At around 15-18°C (slightly below room temperature)", category: "consumer", why: "Full reds show best slightly below modern room temperature (15-18°C); too warm and alcohol dominates. Whites and sparkling are served cooler to preserve freshness." }
];

const THEORY_CATEGORY_LABELS = {
  viticulture: "Viticulture",
  vinification: "Winemaking",
  france: "France",
  italy: "Italy",
  iberia: "Spain & Portugal",
  germanic: "Germany, Austria & Tokaj",
  newworld: "New World",
  sparkling: "Sparkling",
  fortified: "Fortified",
  consumer: "Wine & the consumer"
};
